### ISSUE TITLE
Display glitch on tab refresh/new tab with Digital Clock Enabled

### ISSUE THREAD

**Issue by prem-k-r** [XengShi/materialYouNewTab#112]
When the digital clock is enabled, occasionally, upon opening or refreshing a new tab, the analog display briefly appears for a split second. Although it happens infrequently, the visual glitch only lasts for a fraction of a second and is not a major issue.

**Comment by ceskyDJ** [comment]
A similar problem is with other stuff (editable text, humidity, etc.), too: https://www.awesomescreenshot.com/video/32902473?key=fdaf9138522e180e06f8b8726944cdbc.

**Comment by prem12321kumar** [comment]
Editable text, I have fixed in #107 
for Humidity(default=Humidity), Feels(default=Feels) and Location(default=Earth), it happens cause until it fetches the weatherdata it shows the default one. It doesnt check data every second but when reloaded(refreshed or new tab opened)

**Comment by prem12321kumar** [comment]
> Ok, I see. It's a little weird, when it's in a different language than the rest of the page. Could you make it translatable (or maybe existing translations could be reused here)?

I have already translated that too.. can you confirm if you are using latest version

https://github.com/user-attachments/assets/d9a10e7b-5ec8-40cf-a094-c321919051c5

**Comment by ceskyDJ** [comment]
Oh, sorry. I'll check it out.

**Comment by ceskyDJ** [comment]
You're right, it works in the last commit of `main`.

**Comment by prem12321kumar** [comment]
fixed date loading: Immediately date is updated when clock is analog

**Comment by prem-k-r** [comment]
> @prem-k-r Can you check all the issues and tell XengShi to close the issue by mentioning him!...

Ok

**Comment by itz-rj-here** [comment]
@prem-k-r i think this issue is fixed. can we close this now?

**Comment by prem-k-r** [comment]
I don't think so.
It still showing up and that too in default blue color.
#81

**Comment by itz-rj-here** [comment]
> I don't think so. It still showing up and that too in default blue color. #81

huh. mmm... looks like we need to look into it deeply. :)
