### ISSUE TITLE
[Bug] Colour glitches on start since last update

### ISSUE THREAD

**Issue by ZiClaud** [XengShi/materialYouNewTab#308]
https://github.com/user-attachments/assets/ca5b7884-319d-43d3-b119-48fadbc4cc1a

It only happens when I have the page open

https://github.com/user-attachments/assets/2683677c-d0e2-433b-8f68-b894ed49c51f

It also happens with other colours

**Comment by giwih** [comment]
I think for some reason the theme you selected is not saved, and color glitches are caused by another bug I fixed in - #304 , do you have any problems with saving other settings?

**Comment by ZiClaud** [comment]
> I think for some reason the theme you selected is not saved, and color glitches are caused by another bug I fixed in - #304 , do you have any problems with saving other settings?

Nope, no problems with saves, just with the colour, and just on Firefox.
There's still the same problem while using https://xengshi.github.io/materialYouNewTab/, so I think that it's either because of some extension I use, or something like that.

Also, the same exact thing happens on mobile (I use the Firefox app).

**Comment by prem-k-r** [comment]
Is it fixed with recent PRs merging? 
https://github.com/XengShi/materialYouNewTab/archive/refs/heads/main.zip

**Comment by ZiClaud** [comment]
> Is it fixed with recent PRs merging? [`refs/heads/main`.zip](https://github.com/XengShi/materialYouNewTab/archive/refs/heads/main.zip)

I mean, sort of.
Now it won't appear the glitched theme, but it still resets the theme to the red one.
Also, the second attachment shows the console.

https://github.com/user-attachments/assets/a9801e08-de91-4208-825d-07fdc64238fc


https://github.com/user-attachments/assets/6dc9e94c-1b49-4fec-8125-56ba011b7c30

**Comment by prem-k-r** [comment]
That's odd..
It seems some issue with custom color

**Comment by giwih** [comment]
firefox has a different browser engine, firefox restores the last value of color picker, and when duplicate/open a new tab triggers EventListener, which updates the theme, the default color picker is #ea1010, if you put for example some purple, then when you open a new tab will be purple.
